version: '3.8'

services:
  # Development service with volume mounts for live code editing
  mcp-server-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for development
      - ./src:/app/src
      - ./tests:/app/tests
      # Preserve uv cache and dependencies
      - uv-cache:/app/.uv-cache
    environment:
      # Development environment variables
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      # Add your custom environment variables here
      # - API_KEY=${API_KEY}
    stdin_open: true
    tty: true
    # For stdio-based MCP (most common)
    command: ["uv", "run", "mcp"]
    
    # For HTTP-based MCP servers, uncomment these lines:
    # ports:
    #   - "8000:8000"
    # command: ["uv", "run", "python", "-m", "src.mcp_server_template.server", "--host", "0.0.0.0", "--port", "8000"]

  # Production service without development mounts
  mcp-server-prod:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # Production environment variables
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      # Add your custom environment variables here
      # - API_KEY=${API_KEY}
    restart: unless-stopped
    # For stdio-based MCP (most common)
    command: ["uv", "run", "mcp"]
    
    # For HTTP-based MCP servers, uncomment these lines:
    # ports:
    #   - "8000:8000"
    # command: ["uv", "run", "python", "-m", "src.mcp_server_template.server", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  uv-cache: